### ISSUE TITLE
Add feedback/issue page

### ISSUE THREAD

**Issue by anonymous-sidhax** [anonymous-sidhax/Django-URL-Shortner#23]
- so that users can tell their issues or give suggestions.

**Comment by rockingrohit9639** [comment]
Should it be rendered when the user clicks on Report an Issue?

**Comment by anonymous-sidhax** [comment]
Let's create a different page guys. About us page, we will add all the info about ourselves and our collaborators - we have proper content to fill up the page.
 
For Feedback page only a form is enough like:
- Report a bug
- Feature Request
- Enhancement

Etc
