### ISSUE TITLE
Homepage Frontend Changes (index.html)

### ISSUE THREAD

**Issue by anonymous-sidhax** [anonymous-sidhax/Django-URL-Shortner#5]
- Increase Original URL textfield size so that the text is readable.
- Shorten button is not looking like clickable button (It looks like a text currently).
- After login, remove the sucessful login message after few seconds. (Same for logout message) - The message is not closable even after clicking the exit button.

**Comment by ghost** [comment]
We have to write JavaScript for closing the button and I will write the code today for this

**Comment by rockingrohit9639** [comment]
I have fixed these issues. Check my recent PR.
